server:
  port: 9097
  
 
spring:
    application:
      name: API-GATEWAY
    cloud:
       gateway:
        routes:
        - id: brand-category-service
          uri: http://localhost:9090
          predicates:
            - Path=/api/brands/**
            - Path=api/categories/**
        - id: product-service
          uri: http://localhost:9091
          predicates:
            - Path=/api/products/**
        - id: search-service
          uri: http://localhost:9092
          predicates:
            - Path=/api/search/**
        - id: order-service
          uri: http://localhost:9093
          predicates:
            - Path=/api/orders/**